platform :ios, '14.0'
use_frameworks!

target 'NearbyBridge' do
  # Google's official Nearby Connections SDK for iOS.
  pod 'NearbyConnections', '~> 1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
